matrix:
  include:
    - language: scala
      jdk:
        - openjdk8
      script:
        - cd $TRAVIS_BUILD_DIR/scala-way; sbt 'set scalaVersion := dottyLatestNightlyBuild.get' compile
    - language: haskell
      cabal:
        - "2.4"
      ghc:
        - "8.6.3"
      before_install:
        - cd haskell-way  
      script:
        - cd $TRAVIS_BUILD_DIR/haskell-way; cabal v2-test


