matrix:
  include:
    - language: scala
      scala:
      - 2.12.8
      script:
      - cd $TRAVIS_BUILD_DIR/scala-way; sbt compile test
    - language: haskell
      ghc:
        - "8.6.3"
      script:
        - cd $TRAVIS_BUILD_DIR/haskell-way; cabal v2-test


